// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArrowUpRight: typeof import('./src/components/icon/ArrowUpRight.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GitHub: typeof import('./src/components/icon/GitHub.vue')['default']
    Instagram: typeof import('./src/components/icon/Instagram.vue')['default']
    Linkedin: typeof import('./src/components/icon/Linkedin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stars: typeof import('./src/components/Stars.vue')['default']
    Twitter: typeof import('./src/components/icon/Twitter.vue')['default']
    User: typeof import('./src/components/icon/User.vue')['default']
  }
}

export { }
